# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lh_LrLTwWuCO2UFirQaXCUVwK1xvslcD
"""

# 라이브러리 import
import requests
import json

area = input("검색할 지역을 입력하세요.:")

# url 입력
url = 'http://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getMsrstnAcctoRltmMesureDnsty?serviceKey=u9bHlUS%2F46NMv3xOH76XAix6WIlJKcnWln92nFP7BSP9GKYIPKr5VHPxPhZRpH8jOtSBEdcECq18kXmLdb1rPw%3D%3D&returnType=json&numOfRows=100&pageNo=1&stationName='+area+'&dataTerm=DAILY&ver=1.0'
# url 불러오기
response = requests.get(url)

#데이터 값 출력해보기
contents = response.text

try:
    #문자열을 json으로 변경
    json_ob = json.loads(contents)
    #print(json_ob)
    #print(type(json_ob)) #json타입 확인

    # 필요한 내용만 꺼내기
    pm10_value = json_ob['response']['body']['items'][0]['pm10Value']

    # 결과를 출력
    print(f'미세먼지(PM10) 농도: {pm10_value} μg/m³')
except Exception as e:
    print(f'오류 발생: {e}')